### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by raismaulana** [mirzaakhena/gogen#4]
I do this in my project directory,
```
go get github.com/mirzaakhena/gogen
go install $GOPATH/src/github.com/mirzaakhena/gogen/
```
but result an error.
`stat /src/github.com/mirzaakhena/gogen: directory not found`

Am I missing something? Should i clone this repo to $GOPATH/src/github.com/mirzaakhena/gogen/ ?

Environment:
Ubuntu 20.04
go 1.16.6

**Comment by mirzaakhena** [comment]
Hi @raismaulana 

You can try just
```
go install
```

i will to fix the README for installation.

**Comment by raismaulana** [comment]
Saya ada masalah install. Berikut langkah yang saya lalui:

1. Saya install dulu pakai `go get github.com/mirzaakhena/gogen`, dari proses go get akan download dan build sehingga di direktori $GOPATH akan menghasilkan file dan direktori `$GOPATH/bin/gogen` dan `$GOPATH/pkg/mod/github.com/mirzaakhena/gogen@v1.0.0-beta.1`
2. Kemudian saya membuat sebuah projek di direktori `~/projek_golang/projek1/`
3. Selanjutnya membuat inisialiasi go.mod `go mod init projek1` di direktori projek1
4. Kemudian, saya mengetik perintah `gogen init` dan terjadi error 
    `stat /home/raiz/go/src/github.com/mirzaakhena/gogen/templates/default: no such file or directory`

informasi tambahan:
$GOPATH = /home/raiz/go/

**Comment by mirzaakhena** [comment]
Sorry for late replay since i was very busy.
In the latest version _../gogen/templates/default_ should not used anymore. Since i already use embed
I already release the latest version. Maybe you can try it.

Also i already try to run in ubuntu (via docker since i am using mac) 
i try **go build** to create an gogen executable and **gogen init** is success.

Anyway thanks for reporting this issue.

**Comment by raismaulana** [comment]
Nice, it's working now using the latest version. i don't need to `go build` either, because `go get` took care everything.
